### ISSUE TITLE
Is the link valid now?

### ISSUE THREAD

**Issue by abhinav-adtechs** [ujjwal96/VIT-photo-downloader#1]

**Comment by r00tdaemon** [comment]
Yes, just checked. But you need to login and get the session cookie first

**Comment by abhinav-adtechs** [comment]
Please update the readme. 
I am having trouble using it.

**Comment by r00tdaemon** [comment]
Updated. If you are sill having issues, tell me.

**Comment by abhinav-adtechs** [comment]
Is there a certificate issue or do I not have any library installed?
<img width="569" alt="screen shot 2016-08-23 at 4 47 33 pm" src="https://cloud.githubusercontent.com/assets/13555405/17890101/7273a8a6-6951-11e6-90fa-7625b4519b58.png">

**Comment by r00tdaemon** [comment]
I think you're not copying the cookie correctly. Copy the whole thing, like:
logstudregno=15BCE0571; ASPSESSIONIDSUBRCTSC=IBxxxxxxxxxxxxxxxxxxxxMJ

**Comment by abhinav-adtechs** [comment]
Same error. 🙈

**Comment by r00tdaemon** [comment]
I'm using default library so that shouldn't be an issue

**Comment by abhinav-adtechs** [comment]
Okay, no problem, we will look into it in the next meeting.

**Comment by r00tdaemon** [comment]
Are you logging out after copying the cookie?? 
Don't do that. Because then the cookie expires

**Comment by abhinav-adtechs** [comment]
I am not doing that, there is some kind of redirection to logout done by VIT people it seems.

**Comment by r00tdaemon** [comment]
Don't know. It is working fine on my pc
